server:
  port: 8207
spring:
  application:
    name: service-orders
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  data:
    mongodb:
      uri: mongodb://192.168.253.128:27017/test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/yygh_order?characterEncoding=utf-8&useSSL=false
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  redis:
    database: 0
    host: localhost
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 1800000
  rabbitmq:
    host: 192.168.253.128
    virtual-host: /
    password: guest
    username: guest
    port: 5672

weixin:
  pay:
    #关联的公众号appid
    appid: wx74862e0dfcf69954
    #商户号
    partner: 1558950191
    #商户key
    partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  cert: E:\\apiclient_cert.p12
mybatis-plus:
  mapper-locations: classpath:com/atguigu/yygh/order/mapper/xml/*.xml